['loadAssets',
 'populate',
 'inlineAssets',
 'externalizeAssets',
 'bundleAssets',
 'moveAssets',
 'moveAssetsToDirectory',
 'moveAssetsToNewRoot',
 'registerLabelsAsCustomProtocols',
 'minifyAssets',
 'prettyPrintAssets',
 'runJavaScriptConditionalBlocks',
 'flattenStaticIncludes',
 'drawGraph',
 'addCacheManifestSinglePage',
 'addCacheManifestSiteMap',
 'checkRelationConsistency',
 'spriteBackgroundImages',
 'postProcessBackgroundImages',
 'renameAssetsToMD5Prefix',
 'writeAssetsToDisc',
 'noop',
 'serial',
 'parallel',
 'reportErrorAndTerminate'
].forEach(function (transformName) {
    exports[transformName] = require('./' + transformName);
});
