['loadAssets',
 'populate',
 'inlineAssets',
 'bundleJavaScriptAndCSS',
 'moveAssets',
 'moveAssetsToDirectory',
 'registerLabelsAsCustomProtocols',
 'minifyAssets',
 'executeJavaScript',
 'flattenStaticIncludes',
 'drawGraph',
 'addCDNPrefix',
 'addCacheManifestSinglePage',
 'addCacheManifestSiteMap',
 'checkRelationConsistency',
 'spriteBackgroundImages',
 'addPNG8FallbackForIE6',
 'renameAssetsToMD5Prefix',
 'writeAssetsToDisc',
 'noop',
 'serial',
 'parallel',
 'escapeToCallback'].forEach(function (transformName) {
    exports[transformName] = require('./' + transformName)[transformName];
});
